# Generated by Django 5.0.6 on 2024-06-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('flavor', models.CharField(max_length=100)),
                ('phase', models.CharField(choices=[('F', 'Frozen'), ('M', 'Melted'), ('S', 'Solid')], max_length=1)),
            ],
        ),
    ]
